version: "3.6"
services:
  app:
    build: .
    container_name: pchtr
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "8000:8000"
      - "9229:9229"
    depends_on:
      - mongo
    environment:
      MONGO_URL: mongodb://mongo:27017/pechinchator
      MONGO_TEST_URL: mongodb://mongo:27017/pechinchator_test
  mongo:
    image: mvertes/alpine-mongo:4.0.3-0
    container_name: pchtr-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
  node_modules:
